name: Continuos integration

on: 
  push:
    branches: 
      - custom 
      - master 

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - uses:  ayalaluquez/slack-message-github-action@master
        env:
          WEBHOOK_URL: ${{secrets.SLACK_WEBHOOK_URL}}
          SLACK_CHANNEL: ${{secrets.SLACK_NOTIFICATION_CHANNEL}}
          MESSAGE: Compilation ends
          STATUS: ${{job.status}}
